---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Use this code to set up the full state dataset

hist <- read.delim("raw-data/ncvhis_Statewide.txt")
reg <- read.delim("raw-data/ncvoter_Statewide.txt")

# Make datasets smaller before joining them, otherwise we get a warning that says "vector memory exhausted"

hist_small <- hist %>% 
  select(county_id, county_desc, voter_reg_num, election_lbl, voting_method, voted_party_cd)

# Only include people who turned 18 in 2012 (people who were born in 1994)

reg_small <- reg %>% 
  select(voter_reg_num, zip_code, race_code, ethnic_code, birth_state, registr_dt, birth_year) %>% 
  filter(birth_year == 1994)

# Use full join to merge both datasets

full_voter <- full_join(hist, reg, by=c("voter_reg_num"))

```


```{r}
vote_cohort <- full_voter %>% 
  
  # Create a variable which contains the election, but as a string rather than a
  # date. This is so that we can cast these into variables later when we make
  # our data wider. I'm only relabeling for four elections, since I'm going to
  # filter our dataset to only include these four elections
  
  mutate(election = recode_factor(election_lbl, `11/06/2012` = "gelection_2012",
                `11/04/2014` = "gelection_2014",
                `11/08/2016` = "gelection_2016",
                `11/06/2018` = "gelection_2018")) %>% 
  
  filter(election == "gelection_2012" | election == "gelection_2014" | election == "gelection_2016" | election == "gelection_2018") %>% 

  # Create a dummy variable that signifies if a vote was cast by a mail-in
  # absentee ballot. NC offers several type of absentee voting, but we're only
  # interested in mail-in absentees. All other forms of absentee voting requires
  # in-person precense and we will count this as an in-person vote

  mutate(absentee = ifelse(voting_method == "ABSENTEE BY MAIL", "Absentee", "Not Absentee")) %>% 
  
  # Create a variable for each of the elections and make the value equal to
  # "Absentee", "Not Absentee", "No Vote"
  
  pivot_wider(names_from = election, values_from = absentee, values_fill = list(absentee  = "No Vote")) %>% 
  
 
    # Identify voters as part of the control or treatment group
  
  mutate(treatment = ifelse(gelection_2012 == "Absentee", TRUE, FALSE),
  
         # Create election outcome variables
         
         outcome_2012 = ifelse(gelection_2012 != "No Vote", TRUE, FALSE),
         outcome_2014 = ifelse(gelection_2014 != "No Vote", TRUE, FALSE),
         outcome_2016 = ifelse(gelection_2016 != "No Vote", TRUE, FALSE),
         outcome_2018 = ifelse(gelection_2018 != "No Vote", TRUE, FALSE))

 # Only include voters who voted in the 2012 election

tail(vote_cohort)
```

```{r}
treatment_outcomes <- vote_cohort %>% 
  
  # Narrow down to the columnms we need
  
  select(treatment, outcome_2012, outcome_2014, outcome_2016, outcome_2018) %>% 
  
  # Pivlot longer so that we have a year column
  
  pivot_longer(-treatment, names_to = "year", names_prefix = "outcome_", values_to = "vote") %>% 
  
  # Prepare to create a table that counts the number of votes for each election,
  # shown by treatment group
  
  group_by(treatment, year, vote) %>% 
  arrange(year) %>% 
  count() %>% 
  
  # Create a column which shows the percentage of each group that voted in each election
  
  mutate(perc_treatment = round(100*ifelse(treatment == TRUE, n/56, n/738), digits = 2))


treatment_outcomes %>% 
  
  # We only need to plot the percentage of those that vote, so we only need data
  # for vote = TRUE
  
  filter(vote == TRUE) %>% 
  ggplot(aes(x= year, y= perc_treatment, fill = treatment)) +
  
  # We already calculated the percentage up above, so we can set stat =
  # "identity"
  
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(title = "General Election Turnout Among Voters in Alamance, NC\nWho Turned 18 and Voted for the First Time in 2012", subtitle = "Voters whose first ballots were cast by Absentee Ballots are in the Treatment group", x = "General Election Year", y = "Percent that Cast Ballots", caption = "Explanation for why 2012 is 100%") +
  
  # Add data labels
  
  geom_text(aes(label = perc_treatment), position = position_dodge(.9), vjust = 2) +
  theme_classic()


```


